stages:

  pre_commit:
    cmd: pre-commit run --all-files  && touch pre_commit.flag # Suppresses warnings 8 (dash length), 24 (\labels inside floats), and 1 (trailing whitespace following and command)
    deps:
      - .pre-commit-config.yaml
      - main.tex
      - ch_1_introduction.tex
      - ch_2_safety.tex
      - ch_3_machine_learning.tex
      - ch_4_adversaries.tex
      - ch_5_verification_and_validation.tex
      - ch_6_summary_of_contributions.tex
      - papers
    outs:
      - pre_commit.flag
  check_tex:
    foreach:
      - ch_1_introduction.tex
      - ch_2_safety.tex
      - ch_3_machine_learning.tex
      - ch_4_adversaries.tex
      - ch_5_verification_and_validation.tex
      - ch_6_summary_of_contributions.tex
      - main.tex
    do:
      cmd: >- #-n 24 -n 8 -n 1 -n 45 -n 17 -n 9 -n 23 # Suppresses warnings 8 (dash length), 24 (\labels inside floats),  1 (trailing whitespace following a command), 45 (prefers \[]\ over $$)
        chktex -q -V ${item} -n 24 -n 8 -n 1 -n 45 -n 17 -n 9 -n 23 && touch ${item}.chktex.flag
      deps:
        - ${item}
        - papers
      outs:
        - ${item}.chktex.flag
  # first_run:
  #   cmd: pdflatex  main.tex 
  #   deps:
  #     - main.tex
  #     - library_sample.bib
  #     - ch_1_introduction.tex
  #     - ch_2_safety.tex
  #     - ch_3_machine_learning.tex
  #     - ch_4_adversaries.tex
  #     - ch_5_verification_and_validation.tex
  #     - ch_6_summary_of_contributions.tex
  #     - pre_commit.flag
  #     - ch_1_introduction.tex.chktex.flag
  #     - ch_2_safety.tex.chktex.flag
  #     - ch_3_machine_learning.tex.chktex.flag
  #     - ch_4_adversaries.tex.chktex.flag
  #     - ch_5_verification_and_validation.tex.chktex.flag
  #     - ch_6_summary_of_contributions.tex.chktex.flag
  #     - main.tex.chktex.flag
  #   outs:
  #     - main.aux
  #     - main.log
  #     - main.out
  # big_run:
  #   cmd: pdflatex main.tex && biber main && pdflatex  main.tex && pdflatex  main.tex
  #   deps:
  #     - main.tex
  #     - library_sample.bib
  #     - main.aux
  #     - main.log
  #     - main.out
  #   outs:
  #     - main.bbl
  #     - main.blg
  #     - main.pdf
  