stages:

  pre_commit:
    cmd: pre-commit run --all-files  && touch pre_commit.flag # Suppresses warnings 8 (dash length), 24 (\labels inside floats), and 1 (trailing whitespace following and command)
    deps:
      - .pre-commit-config.yaml
      - main.tex
      - ch_1_introduction.tex
      - ch_2_safety.tex
      - ch_3_machine_learning.tex
      - ch_4_adversaries.tex
      - ch_5_verification_and_validation.tex
      - ch_6_summary_of_contributions.tex
      - papers
    outs:
      - pre_commit.flag
  check_tex:
    foreach:
      - ch_1_introduction.tex
      - ch_2_safety.tex
      - ch_3_machine_learning.tex
      - ch_4_adversaries.tex
      - ch_5_verification_and_validation.tex
      - ch_6_summary_of_contributions.tex
      - main.tex
    do:
      cmd: >- #-n 24 -n 8 -n 1 -n 45 -n 17 -n 9 -n 23 # Suppresses warnings 8 (dash length), 24 (\labels inside floats),  1 (trailing whitespace following a command), 45 (prefers \[]\ over $$)
        chktex -q -V ${item} -n 24 -n 8 -n 1 -n 45 -n 17 -n 9 -n 23 && touch ${item}.chktex.flag
      deps:
        - ${item}
        - papers
      outs:
        - ${item}.chktex.flag
  # render_papers:
  #   foreach:
  #     - input: papers/paper1
  #       output: papers/Paper1.pdf
  #     - input: papers/paper2
  #       output: papers/Paper2.pdf
  #     - input: papers/paper3
  #       output: papers/Paper3.pdf
  #     - input: papers/paper4
  #       output: papers/Paper4.pdf
  #     - input: papers/paper5
  #       output: papers/Paper5.pdf
  #     - input: papers/paper6
  #       output: papers/Paper6.pdf
  #   do:
  #     deps:
  #       - ${item.input}
  #     outs:
  #       - ${item.output}
  #     cmd: >-
  #       cd ${item.input} && dvc repro && touch ${item.input}.flag
  first_run:
    cmd: pdflatex  main.tex 
    deps:
      - main.tex
      - library_sample.bib
      - ch_1_introduction.tex
      - ch_2_safety.tex
      - ch_3_machine_learning.tex
      - ch_4_adversaries.tex
      - ch_5_verification_and_validation.tex
      - ch_6_summary_of_contributions.tex
      - pre_commit.flag
      - ch_1_introduction.tex.chktex.flag
      - ch_2_safety.tex.chktex.flag
      - ch_3_machine_learning.tex.chktex.flag
      - ch_4_adversaries.tex.chktex.flag
      - ch_5_verification_and_validation.tex.chktex.flag
      - ch_6_summary_of_contributions.tex.chktex.flag
      - main.tex.chktex.flag
      - papers/Paper1.pdf
      - papers/Paper2.pdf
      - papers/Paper3.pdf
      - papers/Paper4.pdf
      - papers/Paper5.pdf
      - papers/Paper6.pdf
      - papers/paper1.flag
      - papers/paper2.flag
      - papers/paper3.flag
      - papers/paper4.flag
      - papers/paper5.flag
      - papers/paper6.flag
    outs:
      - main.aux
      - main.log
      - main.out
  big_run:
    cmd: latexmk -pdf -use-make main.tex
    deps:
      - main.tex
      - library_sample.bib
      - main.aux
      - main.log
      - main.out
      - .latexmkrc
    outs:
      - main.bbl
      - main.blg
      - main.pdf
  