stages:
  git_clone_papers:
    foreach:
      - path: paper1
        url : https://github.com/simplymathematics/springer-ai-review.git
      - path:  paper2
        url : https://github.com/simplymathematics/KDD-Paper-EAI-AISEC.git
      - path:  paper3
        url: https://github.com/simplymathematics/ml_afr.git
      - path:  paper4
        url: https://github.com/simplymathematics/kepler-ml.git
      - path:  paper5
        url: https://github.com/simplymathematics/Gzip-KNN.git
      - path:  paper6
        url: https://github.com/simplymathematics/deckard_paper.git
    do: 
      desc:
        Creates submodules for each of the above repositories in the path specified.
      cmd: >-
        (git clone ${item.url} ${item.path}) || echo "already cloned" && 
        cd ${item.path} &&
        git submodule init &&
        git submodule update --recursive --remote && 
        dvc repro ./dvc.yaml