stages:
  git_clone_papers:
    foreach: ${papers}
    do: 
      desc:
        Creates submodules for each of the above repositories in the path specified if it does not exist.
        Otherwise, it updates the submodule.
      cmd: >-
        ( git clone ${item.url} ${item.path} && cd ${item.path} && git submodule init && git submodule update --recursive --remote ) ||
        ( echo "already cloned" &&  cd ${item.path}  && git pull )

  reproduce_papers:
    foreach: ${papers}
    do:
      desc:
        Reproduces the paper in the path specified using dvc repro.
        Copies the output pdf to the root directory and adds it to git.
        Commits and pushes the changes to the remote repository.
      cmd: >-
        cd ${item.path} && 
        dvc repro &&
        cp ${item.input_pdf} ../${item.output_pdf} 
      outs:
        - ${item.output_pdf}:
            cache: false
            persist: true
      
